# config file for circleci
version: 2 
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: j256-ormlite-android-{{ checksum "pom.xml" }}
      - run:
          name: Get maven project dependencies
          command: mvn -P testing -U dependency:go-offline compile
      # save the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: j256-ormlite-android-{{ checksum "pom.xml" }}
      - run:
          name: mvn package
          command: mvn -P testing package
      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      - store_test_results: 
          path: target/surefire-reports
      - run:
          name: Generate coverage report using jacoco
          command: mvn jacoco:report
      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
